#!/bin/bash
cd $OPENSHIFT_REPO_DIR
cp config-template.json config.json
sed -i 's/@OPENSHIFT_NODEJS_IP@/'"$OPENSHIFT_NODEJS_IP"'/g' config.json
sed -i 's/@OPENSHIFT_NODEJS_PORT@/'"$OPENSHIFT_NODEJS_PORT"'/g' config.json
sed -i 's/@OPENSHIFT_MONGODB_DB_HOST@/'"$OPENSHIFT_MONGODB_DB_HOST"'/g' config.json
sed -i 's/@OPENSHIFT_MONGODB_DB_PORT@/'"$OPENSHIFT_MONGODB_DB_PORT"'/g' config.json